USE [master]
GO

/****** Object:  Database [TaskSystemDb]    Script Date: 28-Mar-18 00:36:20 ******/
CREATE DATABASE [TaskSystemDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TaskSystemDb', FILENAME = N'.\TaskSystemDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TaskSystemDb_log', FILENAME = N'.\TaskSystemDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TaskSystemDb] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TaskSystemDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TaskSystemDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TaskSystemDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TaskSystemDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TaskSystemDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TaskSystemDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [TaskSystemDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TaskSystemDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TaskSystemDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TaskSystemDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TaskSystemDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TaskSystemDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TaskSystemDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TaskSystemDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TaskSystemDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TaskSystemDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TaskSystemDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TaskSystemDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TaskSystemDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TaskSystemDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TaskSystemDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TaskSystemDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TaskSystemDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TaskSystemDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TaskSystemDb] SET  MULTI_USER 
GO

ALTER DATABASE [TaskSystemDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TaskSystemDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TaskSystemDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TaskSystemDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TaskSystemDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TaskSystemDb] SET QUERY_STORE = OFF
GO

USE [TaskSystemDb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TaskSystemDb] SET  READ_WRITE 
GO




USE [TaskSystemDb]
GO

/****** Object:  Table [dbo].[Prerequisities]    Script Date: 28-Mar-18 00:37:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Prerequisities](
	[Id] [uniqueidentifier] NOT NULL,
	[TaskId] [uniqueidentifier] NOT NULL,
	[PrerequisityId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_Prerequisities] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO




USE [TaskSystemDb]
GO

/****** Object:  Table [dbo].[Tasks]    Script Date: 28-Mar-18 00:37:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tasks](
	[Id] [uniqueidentifier] NOT NULL,
	[UserID] [uniqueidentifier] NOT NULL,
	[Prerequisities] [bit] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Time] [time](7) NOT NULL
) ON [PRIMARY]
GO




USE [TaskSystemDb]
GO

/****** Object:  Table [dbo].[Users]    Script Date: 28-Mar-18 00:38:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Users](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[PasswordHash] [varchar](50) NOT NULL,
	[IsAdmin] [bit] NOT NULL
) ON [PRIMARY]
GO


--Creates Initial User
--name: testuser password: testuser
Insert into TaskSystemDb.dbo.Users  (Id,Name,Email,PasswordHash,IsAdmin)
 values (NEWID(),'testuser','testuser@testuser.com','5d9c68c6c50ed3d02a2fcf54f63993b6',1);